---
- name: Install essential packages and Set timezone
  hosts: new_vm
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure the package cache is up to date
      apt:
        update_cache: yes

    - name: Install essential packages
      apt:
        name:
          - git
          - curl
          - wget
          - htop
          - stow
          - tmux
          - ansible
          - stow
        state: present
        update_cache: yes
    
    - name: Set timezone
      become: yes
      timezone:
        name: "America/Toronto"
