---
- name: Provision Proxmox VM
  hosts: proxmox
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Debug Proxmox VM creation payload
      debug:
        msg: 
          {
            "vmid": "{{ proxmox_vm_id }}",
            "name": "{{ proxmox_vm_name }}",
            "cores": "{{ proxmox_cores }}",
            "memory": "{{ proxmox_memory }}",
            "net0": "virtio,bridge=vmbr0",
            "scsi0": "{{ proxmox_storage }}:32",
            "boot": "cdn",
            "serial0": "socket",
            "ostype": "l26",
            "cdrom": "{{ proxmox_iso_path }}"
          }
          
    - name: Clone VM from template
      uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/qemu/{{ proxmox_template_vm_id }}/clone"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body_format: json
        body:
          newid: "{{ proxmox_vm_id }}"
          name: "{{ proxmox_vm_name }}"
          full: 1
        validate_certs: no
        status_code: 200
      register: clone_vm_response

    - name: Wait for clone operation to complete
      pause:
        seconds: 40  # Adjust the time as needed

    - name: Debug clone response
      debug:
        var: clone_vm_response.json

    - name: Start the cloned VM
      uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vm_id }}/status/start"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body_format: json
        body: "{}"
        validate_certs: no
        status_code: 200
      when: clone_vm_response.status == 200


    - name: Wait for clone operation to complete
      pause:
        seconds: 60  # Adjust the time as needed

    - name: Ensure QEMU guest agent is installed and running
      wait_for:
        timeout: 300
      delegate_to: "{{ inventory_hostname }}"
      connection: local

    - name: Get the new VM's IP address
      uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vm_id }}/agent/network-get-interfaces"
        method: GET
        headers:
          Content-Type: "application/json"
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        validate_certs: no
      register: vm_network_info

    - name: Set the new VM IP address
      set_fact:
        vm_ip: "{{ vm_network_info.json.result[0].ip-addresses[1].ip-address }}"

- name: Configure static IP on new VM
  hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Wait for VM to be accessible
      wait_for:
        host: "{{ vm_ip }}"
        port: 22
        timeout: 300

    - name: Configure static IP address
      become: yes
      ansible.builtin.template:
        src: static_ip.j2
        dest: /etc/netplan/01-netcfg.yaml

    - name: Apply netplan configuration
      become: yes
      command: netplan apply
      notify:
        - Restart networking

  handlers:
    - name: Restart networking
      become: yes
      service:
        name: systemd-networkd
        state: restarted
