services:
    beaverhabits:
        container_name: beaverhabits
        user: 1000:1000 # User permissions of your docker or default user.
        environment:
            - FIRST_DAY_OF_WEEK=0 # By default, the first day of the week is set as Monday. To change it to Sunday, you can set it as 6.
            - HABITS_STORAGE=USER_DISK # DATABASE stores in a single SQLite database named habits.db. USER_DISK option saves in a local json file.
            - TRUSTED_LOCAL_EMAIL=your@email.com
            - INDEX_HABIT_DATE_COLUMNS=7
            - ENABLE_IOS_STANDALONE=true #E xperiential feature to enable standalone mode on iOS. The default setting is false.
            - INDEX_SHOW_HABIT_COUNT=false # To display the total completed count badge on the main page. The default setting is false.
        volumes:
            - /home/fenkil/pcData/beaverhabits/:/app/.user/ # Change directory to match your docker file scheme.
        ports:
            - 4010:8080
        restart: unless-stopped
        image: daya0576/beaverhabits:latest