---
- name: Provision Proxmox VM
  hosts: proxmox
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Debug Proxmox VM creation payload
      debug:
        msg: 
          {
            "vmid": "{{ proxmox_vm_id }}",
            "name": "{{ proxmox_vm_name }}",
            "cores": "{{ proxmox_cores }}",
            "memory": "{{ proxmox_memory }}",
            "net0": "virtio,bridge=vmbr0",
            "scsi0": "{{ proxmox_storage }}",
            "boot": "cdn",
            "serial0": "socket",    
            "ostype": "l26",
            "cdrom": "{{ proxmox_iso_path }}"
          }
          
    - name: Clone VM from template
      uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/qemu/{{ proxmox_template_vm_id }}/clone"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body_format: json
        body:
          newid: "{{ proxmox_vm_id }}"
          name: "{{ proxmox_vm_name }}"
          full: 1
        validate_certs: no
        status_code: 200
      register: clone_vm_response

    - name: Wait for clone operation to complete
      pause:
        seconds: 45  # Adjust the time as needed - much longer if templateVM is turned on

    - name: Configure VM cores
      uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vm_id }}/config"
        method: PUT
        headers:
          Content-Type: "application/json"
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body_format: json
        body:
          cores: "{{ proxmox_cores }}"
        validate_certs: no
      when: clone_vm_response.status == 200

    - name: Configure VM memory
      uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vm_id }}/config"
        method: PUT
        headers:
          Content-Type: "application/json"
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body_format: json
        body:
          memory: "{{ proxmox_memory }}"
        validate_certs: no
      when: clone_vm_response.status == 200

    - name: Wait for configuration of Cores and Memory operation to complete
      pause:
        seconds: 10  # Adjust the time as needed

    - name: Debug clone response
      debug:
        var: clone_vm_response.json

    - name: Start the cloned VM
      uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vm_id }}/status/start"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "PVEAPIToken={{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body_format: json
        body: "{}"
        validate_certs: no
        status_code: 200
      when: clone_vm_response.status == 200

