---
- name: Install Gitea
  hosts: gitServer
  become: yes
  vars_files:
    - ../coreVMs_vars.yml

  tasks:
    - name: Ensure the Gitea user exists
      user:
        name: "{{ gitea_user }}"
        group: "{{ gitea_group }}"
        home: "{{ gitea_home }}"
        createhome: no  # No need to create the home directory since it's custom
        shell: /bin/bash

    - name: Install required packages
      apt:
        name:
          - git
          - wget
        state: present
        update_cache: yes

    - name: Download Gitea binary
      get_url:
        url: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
        dest: "{{ gitea_binary }}"
        mode: '0755'

    - name: Create Gitea directory structure
      file:
        path: "{{ gitea_home }}/{{ item }}"
        state: directory
        owner: "{{ gitea_user }}"
        group: "{{ gitea_group }}"
        mode: '0755'
      loop:
        - custom
        - data
        - log

    - name: Create Gitea service file
      copy:
        dest: "{{ gitea_service }}"
        content: |
          [Unit]
          Description=Gitea
          After=syslog.target
          After=network.target
          After=mariadb.service mysqld.service postgresql.service memcached.service redis.service

          [Service]
          RestartSec=2s
          Type=simple
          User={{ gitea_user }}
          Group={{ gitea_group }}
          WorkingDirectory={{ gitea_home }}
          ExecStart={{ gitea_binary}} web --config {{ gitea_home }}/custom/conf/app.ini
          Restart=always
          Environment=USER={{ gitea_user}} HOME={{ gitea_home}} GITEA_WORK_DIR={{ gitea_home}}
          
          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Gitea service
      systemd:
        name: gitea
        enabled: yes
        state: started
