---
- name: Install Jellyfin, Audiobookshelf, and Symlink Music Folder
  hosts: mediaServer
  become: yes

  vars:
    pcdata_directory: "/home/fenkil/pcData"
    media_directory: "/media"

  tasks:

    - name: Install necessary packages
      apt:
        name:
          - curl
          - gnupg
          - software-properties-common
        state: present

    - name: Enable Universe repository (Ubuntu only)
      command: add-apt-repository -y universe
      when: ansible_distribution == "Ubuntu"

    - name: Remove existing Jellyfin GPG key directory if it exists
      file:
        path: /etc/apt/keyrings
        state: absent
        force: yes

    - name: Create directory for Jellyfin GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and install Jellyfin GPG key
      shell: curl -fsSL https://repo.jellyfin.org/jellyfin_team.gpg.key | gpg --dearmor -o /etc/apt/keyrings/jellyfin.gpg

    - name: Add Jellyfin repository
      shell: |
        VERSION_OS="$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release )" &&
        VERSION_CODENAME="$( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release )" &&
        DPKG_ARCHITECTURE="$( dpkg --print-architecture )" &&
        echo "Types: deb" > /etc/apt/sources.list.d/jellyfin.sources &&
        echo "URIs: https://repo.jellyfin.org/${VERSION_OS}" >> /etc/apt/sources.list.d/jellyfin.sources &&
        echo "Suites: ${VERSION_CODENAME}" >> /etc/apt/sources.list.d/jellyfin.sources &&
        echo "Components: main" >> /etc/apt/sources.list.d/jellyfin.sources &&
        echo "Architectures: ${DPKG_ARCHITECTURE}" >> /etc/apt/sources.list.d/jellyfin.sources &&
        echo "Signed-By: /etc/apt/keyrings/jellyfin.gpg" >> /etc/apt/sources.list.d/jellyfin.sources

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jellyfin
      apt:
        name: jellyfin
        state: present

    - name: Add Audiobookshelf GPG key and repository
      shell: |
        wget -O- https://advplyr.github.io/audiobookshelf-ppa/KEY.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/adb-archive-keyring.gpg
        curl -s -o /etc/apt/sources.list.d/audiobookshelf.list https://advplyr.github.io/audiobookshelf-ppa/audiobookshelf.list

    - name: Update apt cache after adding Audiobookshelf repository
      apt:
        update_cache: yes

    - name: Install Audiobookshelf
      apt:
        name: audiobookshelf
        state: present

    - name: Create media directory if it doesn't exist
      file:
        path: "{{ media_directory }}"
        state: directory
        mode: '0755'

    - name: Create symbolic link for /media in pcData directory
      file:
        src: "{{ media_directory }}"
        dest: "{{ pcdata_directory }}/media"
        state: link

    - name: Ensure jellyfin user owns the Jellyfin directories
      file:
        path: /var/lib/jellyfin
        owner: jellyfin
        group: jellyfin
        recurse: yes

    - name: Ensure jellyfin user owns the Jellyfin configuration
      file:
        path: /etc/jellyfin
        owner: jellyfin
        group: jellyfin
        recurse: yes

    - name: Enable and start Jellyfin service
      systemd:
        name: jellyfin
        enabled: yes
        state: started


    - name: Enable and start Audiobookshelf service
      systemd:
        name: audiobookshelf
        enabled: yes
        state: started
